// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calcAirService.proto

package calcAirPoll;

public final class CalculateAirPollutionServiceImpl {
  private CalculateAirPollutionServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calcAirService_ConvertMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calcAirService_ConvertMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calcAirService_ConvertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calcAirService_ConvertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calcAirService_RandomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calcAirService_RandomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calcAirService_NumberResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calcAirService_NumberResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calcAirService_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calcAirService_CalculateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calcAirService_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calcAirService_CalculateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calcAirService_NumberMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calcAirService_NumberMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024calcAirService.proto\022\016calcAirService\"B" +
      "\n\016ConvertMessage\022\016\n\006number\030\001 \001(\t\022\020\n\010from" +
      "Base\030\002 \001(\005\022\016\n\006toBase\030\003 \001(\005\"/\n\017ConvertRes" +
      "ponse\022\016\n\006number\030\001 \001(\t\022\014\n\004base\030\002 \001(\005\":\n\rR" +
      "andomRequest\022\017\n\007numbers\030\001 \001(\005\022\013\n\003min\030\002 \001" +
      "(\005\022\013\n\003max\030\003 \001(\005\" \n\016NumberResponse\022\016\n\006num" +
      "ber\030\001 \001(\005\"\275\001\n\020CalculateRequest\022\017\n\007number" +
      "1\030\001 \001(\002\022\017\n\007number2\030\002 \001(\002\022=\n\toperation\030\003 " +
      "\001(\0162*.calcAirService.CalculateRequest.Op" +
      "eration\"H\n\tOperation\022\t\n\005TOTAL\020\000\022\016\n\nDIFFE" +
      "RENCE\020\001\022\022\n\016MULTIPLICATION\020\002\022\014\n\010DIVISION\020" +
      "\003\"4\n\021CalculateResponse\022\016\n\006result\030\001 \001(\002\022\017" +
      "\n\007message\030\002 \001(\t\"\037\n\rNumberMessage\022\016\n\006numb" +
      "er\030\001 \001(\0022\227\002\n\016AirCalcService\022R\n\tcalculate" +
      "\022 .calcAirService.CalculateRequest\032!.cal" +
      "cAirService.CalculateResponse\"\000\022Z\n\025gener" +
      "ateRandomNumbers\022\035.calcAirService.Random" +
      "Request\032\036.calcAirService.NumberResponse\"" +
      "\0000\001\022U\n\raverageValues\022\035.calcAirService.Nu" +
      "mberMessage\032!.calcAirService.CalculateRe" +
      "sponse\"\000(\001B1\n\013calcAirPollB CalculateAirP" +
      "ollutionServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_calcAirService_ConvertMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_calcAirService_ConvertMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calcAirService_ConvertMessage_descriptor,
        new java.lang.String[] { "Number", "FromBase", "ToBase", });
    internal_static_calcAirService_ConvertResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_calcAirService_ConvertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calcAirService_ConvertResponse_descriptor,
        new java.lang.String[] { "Number", "Base", });
    internal_static_calcAirService_RandomRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_calcAirService_RandomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calcAirService_RandomRequest_descriptor,
        new java.lang.String[] { "Numbers", "Min", "Max", });
    internal_static_calcAirService_NumberResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_calcAirService_NumberResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calcAirService_NumberResponse_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_calcAirService_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_calcAirService_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calcAirService_CalculateRequest_descriptor,
        new java.lang.String[] { "Number1", "Number2", "Operation", });
    internal_static_calcAirService_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_calcAirService_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calcAirService_CalculateResponse_descriptor,
        new java.lang.String[] { "Result", "Message", });
    internal_static_calcAirService_NumberMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_calcAirService_NumberMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calcAirService_NumberMessage_descriptor,
        new java.lang.String[] { "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
