// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calcAirService.proto

package calcAirPoll;

public interface CalculateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calcAirService.CalculateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float number1 = 1;</code>
   */
  float getNumber1();

  /**
   * <code>float number2 = 2;</code>
   */
  float getNumber2();

  /**
   * <code>.calcAirService.CalculateRequest.Operation operation = 3;</code>
   */
  int getOperationValue();
  /**
   * <code>.calcAirService.CalculateRequest.Operation operation = 3;</code>
   */
  calcAirPoll.CalculateRequest.Operation getOperation();
}
