// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calcAirService.proto

package calcAirPoll;

public interface NumberMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calcAirService.NumberMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float number = 1;</code>
   */
  float getNumber();
}
