// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calcAirService.proto

package calcAirPoll;

public interface NumberResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calcAirService.NumberResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
