// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alertService.proto

package grpc_examples_airpollution;

public final class airPollutionServiceImpl {
  private airPollutionServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alertService_WorstRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alertService_WorstRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alertService_WorstResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alertService_WorstResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022alertService.proto\022\014alertService\"#\n\014Wo" +
      "rstRequest\022\023\n\013countryName\030\001 \001(\t\"$\n\rWorst" +
      "Response\022\023\n\013countryInfo\030\001 \001(\t2[\n\talertUs" +
      "er\022N\n\021WorstAirPollution\022\032.alertService.W" +
      "orstRequest\032\033.alertService.WorstResponse" +
      "\"\000B7\n\032grpc_examples_airpollutionB\027airPol" +
      "lutionServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_alertService_WorstRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alertService_WorstRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alertService_WorstRequest_descriptor,
        new java.lang.String[] { "CountryName", });
    internal_static_alertService_WorstResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_alertService_WorstResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alertService_WorstResponse_descriptor,
        new java.lang.String[] { "CountryInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
