// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alertService.proto

package grpc_examples_airpollution;

public interface WorstRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alertService.WorstRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string countryName = 1;</code>
   */
  java.lang.String getCountryName();
  /**
   * <code>string countryName = 1;</code>
   */
  com.google.protobuf.ByteString
      getCountryNameBytes();
}
