// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alertService.proto

package grpc_examples_airpollution;

public interface WorstResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alertService.WorstResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string countryInfo = 1;</code>
   */
  java.lang.String getCountryInfo();
  /**
   * <code>string countryInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getCountryInfoBytes();
}
