// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: secondUser.proto

package login_service2;

public final class MathServiceImpl {
  private MathServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConvertMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConvertMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConvertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConvertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RandomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RandomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NumberResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NumberResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CalculateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CalculateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NumberMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NumberMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020secondUser.proto\"B\n\016ConvertMessage\022\016\n\006" +
      "number\030\001 \001(\t\022\020\n\010fromBase\030\002 \001(\005\022\016\n\006toBase" +
      "\030\003 \001(\005\"/\n\017ConvertResponse\022\016\n\006number\030\001 \001(" +
      "\t\022\014\n\004base\030\002 \001(\005\":\n\rRandomRequest\022\017\n\007numb" +
      "ers\030\001 \001(\005\022\013\n\003min\030\002 \001(\005\022\013\n\003max\030\003 \001(\005\" \n\016N" +
      "umberResponse\022\016\n\006number\030\001 \001(\005\"\262\001\n\020Calcul" +
      "ateRequest\022\017\n\007number1\030\001 \001(\002\022\017\n\007number2\030\002" +
      " \001(\002\022.\n\toperation\030\003 \001(\0162\033.CalculateReque" +
      "st.Operation\"L\n\tOperation\022\014\n\010ADDITION\020\000\022" +
      "\017\n\013SUBTRACTION\020\001\022\022\n\016MULTIPLICATION\020\002\022\014\n\010" +
      "DIVISION\020\003\"4\n\021CalculateResponse\022\016\n\006resul" +
      "t\030\001 \001(\002\022\017\n\007message\030\002 \001(\t\"\037\n\rNumberMessag" +
      "e\022\016\n\006number\030\001 \001(\0022\362\001\n\013MathService\0224\n\tcal" +
      "culate\022\021.CalculateRequest\032\022.CalculateRes" +
      "ponse\"\000\022<\n\025generateRandomNumbers\022\016.Rando" +
      "mRequest\032\017.NumberResponse\"\0000\001\0227\n\raverage" +
      "Values\022\016.NumberMessage\032\022.CalculateRespon" +
      "se\"\000(\001\0226\n\013convertBase\022\017.ConvertMessage\032\020" +
      ".ConvertResponse\"\000(\0010\001B#\n\016login_service2" +
      "B\017MathServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ConvertMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConvertMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConvertMessage_descriptor,
        new java.lang.String[] { "Number", "FromBase", "ToBase", });
    internal_static_ConvertResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConvertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConvertResponse_descriptor,
        new java.lang.String[] { "Number", "Base", });
    internal_static_RandomRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RandomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RandomRequest_descriptor,
        new java.lang.String[] { "Numbers", "Min", "Max", });
    internal_static_NumberResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_NumberResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NumberResponse_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CalculateRequest_descriptor,
        new java.lang.String[] { "Number1", "Number2", "Operation", });
    internal_static_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CalculateResponse_descriptor,
        new java.lang.String[] { "Result", "Message", });
    internal_static_NumberMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_NumberMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NumberMessage_descriptor,
        new java.lang.String[] { "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
